name: subscriptions_db
services:
  redis:
    image: redis:alpine
    networks:
      - subscriptions_db_network
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/data
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf:vo
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    restart: always

  db:
    image: postgres:16
    networks:
      - subscriptions_db_network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
      - ./data/init-sql:/docker-entrypoint-initdb.d/:vo

  app:
    build: ..
    image: subscriptions-db
    networks:
      - subscriptions_db_network
    ports:
      - 3005:3000
    volumes:
      - ..:/app
    depends_on:
      - redis
      - db
    command: [ "node", "app.js" ]

networks:
  subscriptions_db_network: {}
